all: hw-part-1.pdf hw-part-2.pdf

hw-part-1.pdf: hw-part-1.tex
	pdflatex hw-part-1.tex
	pdflatex hw-part-1.tex

hw-part-2.pdf: hw-part-2.tex
	pdflatex hw-part-2.tex
	pdflatex hw-part-2.tex

clean:
	rm -rf 	hw-part-1.pdf hw-part-2.pdf
